spring:
  profiles:
    active: ${PROFILE}
  devtools:
    livereload:
      restart:
        enabled: 'true'
      enabled: 'true'
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true